server:
  port: 111

system:
  conf:
    active: prod
    listener: com.sunny.TestListener

test:
  example:
    a: 1a
    b: 2b
    c: 3c
    d: 
  exampleWithNotAnno:
    a2: 1a
    b2: 2b
    c2: 3c
    d2: 